/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example.gradle.plugin;

import groovy.lang.Closure;
import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.gradle.api.plugins.ExtensionContainer;
import org.gradle.testing.base.internal.DefaultTestingExtension;

/**
 * A simple 'hello world' plugin.
 */
public class BetterTestPlugin implements Plugin<Project> {
    public void apply(Project project) {
        project.configure(project, new Closure(project) {
            @Override
            public Object call() {
                System.out.println("testing closure 2");
                //Object testing = project.getExtensions().findByName("testing");
                //System.out.println(testing.getClass().toString());

                //project.getExtensions().create("testing");

                return "";
            }
        });

        project.getTasks().register("betterTest", task -> {
            task.doLast(s -> System.out.println("Hi from plugin 'example.gradle.plugin.greeting'"));
        });
    }
}
